{\rtf1\ansi\ansicpg1251\cocoartf2639
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 HelveticaNeue;}
{\colortbl;\red255\green255\blue255;\red255\green255\blue255;\red25\green25\blue25;\red255\green255\blue255;
\red25\green25\blue25;}
{\*\expandedcolortbl;;\cssrgb\c100000\c100000\c100000;\cssrgb\c13039\c13039\c12925;\cssrgb\c100000\c100000\c99895;
\cssrgb\c13039\c13039\c12925;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs32 \cf2 \cb3 \expnd0\expndtw0\kerning0
FROM amazoncorretto:21\
\
WORKDIR /app\
\
COPY ./target/hello-world.jar \cb5 hello-world\cb3 .jar\
\
ENTRYPOINT ["java", "-jar", "\cb5 hello-world\cb3 .jar"]}